site_name: Lamden Contracting
theme: readthedocs
nav:
    - Home: index.md
    
    - Introduction: 
      - What: intro/intro.md
      - Motivation: intro/motivation.md
      - Philosophy: intro/philosophy.md

    - Quick Start:
      - First Contract: quickstart/import-submit.md
      - Executing Functions: quickstart/methods.md
      - Storing Data: quickstart/storage.md
      - Advanced Features: quickstart/submit.md
      - Testing and Feedback: quickstart/testing.md

    - Key Concepts: 
        - Execution Model: concepts/model.md
        - Valid Code: concepts/valid-code.md
        - Methods: concepts/methods.md
        - Storage: concepts/storage.md
        - Imports: concepts/imports.md
        - Context: concepts/context.md
        - Submission: concepts/submission.md
        - Stamps: concepts/stamps.md
        - datetime Module: concepts/time.md
        - hashlib Module: concepts/hashing.md
        - random Module: concepts/randoms.md

    - Submitting to Lamden: submitting.md